import { capabilities, profile } from '../data/profile';
import { projects } from '../data/projects';
import repositoryData from '../data/repositories.json';
import { ArticleList, ConnectPreview, SectionHead } from '../components/Shared';
import { SystemStack } from '../components/work/ArchitectureDiagram';
export function Home() {
  const featured = ['agent-passport', 'alfred', 'revex'].map(name => repositoryData.repositories.find(r => r.name === name)!);
  return <><section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" aria-hidden="true" />{profile.title} · {profile.location}</p><h1>Designing AI systems<br className="desktop-break" /> that survive<br className="desktop-break" /> <span className="accent">production.</span></h1><p className="hero-lead">I work at the intersection of AI architecture and hands-on engineering—designing agents, retrieval, evaluation, and enterprise systems that operate reliably in production.</p><p className="hero-detail">From strategic architecture and system design to implementation, security, governance, and long-term adoption.</p><div className="hero-actions"><a className="button-primary" href="/work">Explore my work <span aria-hidden="true">↗</span></a><a className="button-quiet" href="/about-me">About me <span aria-hidden="true">→</span></a></div></div><SystemStack /></section>
  <div className="hero-baseline"><span>STRATEGY ↔ ARCHITECTURE ↔ ENGINEERING</span><div><a href="/repos">View repositories ↗</a><a href="/connect">Connect ↗</a></div></div>
  <section className="section"><SectionHead number="01" label="AREAS OF PRACTICE" title="Across the system." /><div className="capability-grid">{capabilities.map(([title, description], i) => <article key={title}><span className="small-index">0{i + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
  <section className="section"><SectionHead number="02" label="SELECTED WORK" title="Architecture, made concrete." href="/work" link="Explore the case studies" /><p className="section-description">Public engineering projects. The problems, boundaries, and decisions behind the code.</p><div className="featured-work">{projects.map((p, i) => <article key={p.slug} className="work-row"><div className="work-index">0{i + 1}<span>{p.kind}</span></div><div><span className="project-name">{p.slug}</span><h3><a href={`/work#${p.slug}`}>{p.title}</a></h3><p>{p.summary}</p><span className="mono muted">{p.focus}</span></div><div className="row-links"><a href={`/work#${p.slug}`}>Case study ↗</a><a href={`/${p.slug}`}>Project ↗</a><a href={`${profile.github}/${p.slug}`}>GitHub ↗</a></div></article>)}</div></section>
  <section className="point-of-view"><p className="eyebrow">03 / HOW I THINK</p><div><h2>Architecture is more<br />than choosing models.</h2><p>I approach AI as a systems problem. Model capability matters, but production outcomes depend just as much on data, evaluation, security, observability, cost, and operational ownership.</p><p>The boundaries between those concerns are where much of the engineering happens.</p><a className="text-link" href="/about-me">Read more about my approach <span aria-hidden="true">↗</span></a></div></section>
  <section className="section"><SectionHead number="04" label="PUBLIC ENGINEERING" title="Open-source engineering." href="/repos" link="Explore all repositories" /><div className="repo-preview-grid">{featured.map(r => <article key={r.name}><div className="repo-topline"><span className="mono">{r.language}</span><span aria-hidden="true">↗</span></div><h3><a href={`/${r.name}`}>{r.name}</a></h3><p>{r.description}</p><div className="row-links horizontal"><a href={`/${r.name}`}>Project ↗</a><a href={r.html_url}>GitHub ↗</a></div></article>)}</div></section>
  <section className="section"><SectionHead number="05" label="WRITING" title="Thinking through the details." href="/writing" link="View all writing" /><ArticleList limit={2} /></section><ConnectPreview /></>;
}
