import { projects, type CaseStudy } from '../data/projects';
import { profile } from '../data/profile';
import { ArchitectureDiagram } from '../components/work/ArchitectureDiagram';
import { PageIntro, ConnectPreview } from '../components/Shared';
export function CaseStudyBody({ project: p }: { project: CaseStudy }) {
  return <><div className="case-problem"><div><h3>Problem & context</h3><p>{p.problem}</p></div><div><h3>Constraints</h3><p>{p.constraints}</p></div></div><ArchitectureDiagram steps={p.flow} caption={p.architecture} /><div className="case-details">{[['Technical decisions', p.decisions], ['Trade-offs', p.tradeoffs], ['Implementation', p.implementation], ['Reliability', p.reliability], ['Security', p.security], ['Evaluation', p.evaluation], ['Operating the system', p.operations], ['Outcome & evidence', p.outcome], ['What the design makes clear', p.lessons]].map(([title, text]) => <div key={title}><h3>{title}</h3><p>{text}</p></div>)}</div><div className="case-links"><a href={`/${p.slug}`}>Project page ↗</a><a href={`${profile.github}/${p.slug}`}>Source & documentation ↗</a><a href={`/writing/${p.article}`}>Related writing ↗</a></div></>;
}
export function Work() {
 return <><PageIntro eyebrow="SELECTED ENGINEERING / PUBLIC EVIDENCE" title="Decisions behind the systems."><p>Problems, constraints, implementation choices, and the trade-offs that remain after a design becomes code.</p><p className="muted">These case studies examine public open-source work and research implementations. They do not represent confidential client projects or imply production adoption.</p></PageIntro><nav className="case-index" aria-label="Case studies">{projects.map((p, i) => <a href={`#${p.slug}`} key={p.slug}><span>0{i + 1}</span>{p.slug}<span aria-hidden="true">↓</span></a>)}</nav>{projects.map((p, i) => <article className="case-study" id={p.slug} key={p.slug}><div className="case-title"><p className="eyebrow">0{i + 1} / {p.kind}</p><span className="project-name">{p.slug}</span><h2>{p.title}</h2><p className="case-summary">{p.summary}</p><p className="mono muted">{p.focus}</p></div><CaseStudyBody project={p} /><p className="source-note">Source: <a href={`${profile.github}/${p.slug}#readme`}>{p.slug} public README</a>. Architecture summary reviewed 21 September 2026. Operational considerations are analysis of the design, not reported deployment results.</p></article>)}<ConnectPreview /></>;
}
