import { ArticleList, articles, type Article, PageIntro, TableOfContents, formatDate } from '../components/Shared';
import { profile } from '../data/profile';
export function Writing() {
 return <><PageIntro eyebrow="ESSAYS / ENGINEERING & ARCHITECTURE" title="Thinking in systems."><p>Technical writing about the decisions that make AI systems useful, reliable, and possible to operate. Agents, retrieval, evaluation, security, and the engineering between them.</p><a className="text-link" href="/feed.xml">Subscribe via RSS ↗</a></PageIntro><ArticleList /><section className="writing-note"><p className="eyebrow">WHY I WRITE</p><h2>Make the reasoning explicit.</h2><p>Writing is a way to examine a decision: the problem it solves, the assumptions it depends on, and the cost of choosing it. These essays connect that reasoning to <a href="/work">public engineering work</a>.</p></section></>;
}
export function ArticlePage({ article }: { article: Article }) {
 const related = articles.filter(a => a.slug !== article.slug);
 return <><div className="breadcrumbs"><a href="/writing">Writing</a><span aria-hidden="true">/</span><span>{article.tags[0]}</span></div><article><header className="article-header"><p className="eyebrow">{article.tags.join(' / ')}</p><h1>{article.title}</h1><p className="article-deck">{article.description}</p><div className="article-byline"><a href="/about-me">{profile.name}</a><time dateTime={article.date}>{formatDate(article.date)}</time><span>{article.readingTime} min read</span>{article.updated && <span>Updated {formatDate(article.updated)}</span>}</div></header><div className="editorial-layout"><TableOfContents headings={article.headings} /><div className="prose" dangerouslySetInnerHTML={{ __html: article.html }} /></div><footer className="article-end"><div><p className="eyebrow">ABOUT THE AUTHOR</p><h2>{profile.name}</h2><p>{profile.title}. I work across AI architecture and hands-on engineering, from problem framing to production operation.</p><a href="/about-me">More about my approach ↗</a></div><div><h2>Explore the code</h2>{article.repositories.map(name => <a key={name} href={`/${name}`}>{name} ↗</a>)}<a href="/work">Related engineering work ↗</a></div></footer></article><section className="related-writing"><p className="eyebrow">CONTINUE READING</p>{related.map(a => <h2 key={a.slug}><a href={`/writing/${a.slug}`}>{a.title} ↗</a></h2>)}<a className="text-link" href="/writing">All writing →</a></section></>;
}
