import { motion } from 'framer-motion';
import { ArrowDown, ArrowUpRight, Cpu, Database, ShieldCheck } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { LinkButton } from './ui/Button';
import { profile } from '../content/data';

const fade = (delay = 0) => ({ initial: { opacity: 0, y: 18 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.8, delay, ease: [0.22, 1, 0.36, 1] } });

export function Hero() {
  return <section id="top" className="relative isolate overflow-hidden pb-20 pt-32 md:pb-28 md:pt-44">
    <div className="pointer-events-none absolute inset-0 -z-10"><div className="absolute inset-0 grid-bg mask-radial-fade opacity-50" /><motion.div aria-hidden className="absolute right-[-10%] top-[-10%] h-[650px] w-[650px] rounded-full bg-accent-400/10 blur-3xl animate-aurora" /><div className="absolute inset-0 noise opacity-[0.04] mix-blend-overlay" /><div className="absolute inset-x-0 bottom-0 h-40 bg-gradient-to-b from-transparent to-ink-950" /></div>
    <div className="container-x"><div className="mb-12 flex items-center gap-3 text-xs font-mono uppercase tracking-[0.22em] text-accent-300/80"><span className="h-px w-10 bg-accent-300/70" /> AI systems / Bengaluru · India</div>
      <div className="grid items-end gap-14 lg:grid-cols-[1.15fr_.85fr]"><div>
        <motion.h1 {...fade()} className="max-w-4xl text-balance text-5xl font-semibold leading-[.96] tracking-tightest text-white md:text-7xl lg:text-[92px]">I build the <span className="gradient-accent">systems</span><span className="block text-white/50">that make AI useful.</span></motion.h1>
        <motion.p {...fade(0.15)} className="mt-7 max-w-2xl text-pretty text-base leading-relaxed text-white/55 md:mt-8 md:text-xl">{profile.tagline} <span className="text-white/70">{profile.summary}</span></motion.p>
        <motion.div {...fade(0.25)} className="mt-10 flex flex-wrap items-center gap-3"><LinkButton href={`mailto:${profile.email}`} variant="primary">Work with me</LinkButton><LinkButton href="#work" variant="secondary">Explore the work</LinkButton></motion.div>
        <motion.div {...fade(0.35)} className="mt-16 grid grid-cols-2 gap-6 border-t border-white/[0.10] pt-7 md:mt-24 md:grid-cols-4"><HeroStat value="50k QPS" label="Retrieval index" /><HeroStat value="&lt; 800ms" label="p99 latency" /><HeroStat value="~70%" label="Incident reduction" /><HeroStat value="&lt; 1 day" label="Eval cycles" /></motion.div>
      </div><motion.div {...fade(0.22)} className="relative hidden lg:block"><div className="rounded-[2rem] border border-white/10 bg-[#0b2027]/85 p-5 shadow-2xl shadow-black/30 backdrop-blur-xl"><div className="mb-8 flex items-center justify-between border-b border-white/10 pb-4"><span className="font-mono text-[10px] uppercase tracking-[.2em] text-white/45">system / live</span><span className="flex items-center gap-2 font-mono text-[10px] text-accent-300"><span className="h-1.5 w-1.5 rounded-full bg-accent-300 shadow-[0_0_10px_#c1f34d]" /> healthy</span></div><div className="space-y-3"><Signal label="model layer" value="frontier / routed" icon={Cpu} /><Signal label="evaluation" value="continuous / 98.4%" icon={ShieldCheck} /><Signal label="data plane" value="fresh / encrypted" icon={Database} /></div><div className="mt-8 border-t border-white/10 pt-5 font-mono text-xs leading-relaxed text-white/45"><span className="text-accent-300">→</span> from first question to production,<br />with the guardrails switched on.</div></div><a href="#work" className="mt-5 inline-flex items-center gap-2 font-mono text-[11px] uppercase tracking-[.16em] text-white/45 transition-colors hover:text-accent-200">See the proof <ArrowDown className="h-3 w-3" /></a></motion.div></div>
    </div></section>;
}

function Signal({ label, value, icon: Icon }: { label: string; value: string; icon: LucideIcon }) { return <div className="flex items-center gap-3 rounded-2xl border border-white/[.08] bg-white/[.03] p-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-accent-300/10 text-accent-300"><Icon className="h-4 w-4" /></span><span className="flex flex-1 flex-col gap-1"><span className="font-mono text-[10px] uppercase tracking-[.14em] text-white/35">{label}</span><span className="text-sm text-white/80">{value}</span></span><ArrowUpRight className="h-3.5 w-3.5 text-white/25" /></div>; }
function HeroStat({ value, label }: { value: string; label: string }) { return <div className="flex flex-col gap-1.5"><span className="text-2xl font-semibold tracking-tighter text-white md:text-3xl">{value}</span><span className="text-xs uppercase tracking-[0.16em] text-white/40">{label}</span></div>; }
